### PR TITLE
2018-02-16 Public meeting notes

### PR DESCRIPTION
**Pull request by mihaiep**
Created 2018-02-16 Public meeting notes.md

### CODE REVIEW

**Comment by mihaiep** [comment]
To close this PR, I want to make sure nothing bad will happen. Not sure how these old commits that are no longer necessary face up, the only modified file should be 2018-02-16-Public-meeting.md . Is it safe to merge this PR? Or do I need to git rebase(I need to take a look on help documentation)? Thanks

**Comment by dshaw** [comment]
@mihaiep I'm not sure how to do that on the web interface. If you want to redo the PR, that's fine too. It might be easier.

**Comment by mihaiep** [comment]
usually I'm using Git Bash on my local directory and then using git commands to sync.

**Comment by dshaw** [comment]
Rebasing should work then.

**Comment by mihaiep** [comment]
I think I need to delete all history (14 old commits) excluding  2018-02-16 Public User Feedback Meeting- ce81ec4.  How should I do this?

**Comment by dshaw** [comment]
I would use `git reset`. https://www.atlassian.com/git/tutorials/resetting-checking-out-and-reverting

**Comment by mihaiep** [comment]
I opened this https://github.com/nodejs/user-feedback/pull/40 to fix old commits

**Pull request closed without merging**
