### PR TITLE
Create Code_of_Conduct.md

### PR DESCRIPTION
**Pull request by mihaiep**
Used the TSC/master/CODE_OF_CONDUCT.md as template

### CODE REVIEW

**Comment by MylesBorins** [comment]
I suggest linking to the tsc CoC rather than copying the text

**Comment by mhdawson** [comment]
I'm hoping we can just land the version in the admin repo and then point to that.  @MylesBorins are you going to land your PR for that soon ?

**Comment by MylesBorins** [comment]
Done

**Comment by mhdawson** [comment]
The code of conduct should just reference this link now. Something along these lines.

This team uses the common Node.js code of conduct found here: https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md

**Comment by mihaiep** [comment]
Thank you for comments and pushing this on patch-1 branch on mihaiep/user-feedback.

**Comment by mikehostetler** [comment]
👍  LGTM

**Pull request merged**
