### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SofiEstevez**
Updated the Read Me with a deadlines timeline :)

### CODE REVIEW

**Comment by mhdawson** [comment]
The formatting does not look right when I view the whole file. I'm also not sure that this belongs on the readme as it is just one of the initiatives.

I think an issue where the items were bulleted lists would be good?

**Comment by SofiEstevez** [comment]
@mhdawson Thanks for helping me Michael! You think it would be ok to close this PR and put this timeline in a new .md called timeline or something like that?

**Comment by mihaiep** [comment]
To update this readme file, please read  https://github.com/nodejs/user-feedback/blob/master/CONTRIBUTING.md; or we need to update the contributing.md?

**Comment by SofiEstevez** [comment]
@mhdawson sorry for the format, I edited. Hope it looks good now :)

**Pull request merged**
